### PR TITLE
Change for definition query

### PR DESCRIPTION
**Pull request by tejashah88**
Changed how definitions are queried to reflect changes on quizlet

### CODE REVIEW

**Comment by tejashah88** [comment]
I just checked the tests and the fixtures aren't reflective of the HTML in quizlet.

**Comment by makenova** [comment]
Hi @tejashah88 thanks for the PR! I haven't touched this in a bit so I'll need a bit to re-familiarize myself with it. This is just a note to let you know I'm not ignoring your PR.

**Review by makenova — APPROVED** [review]
LGTM!

Thanks again!
If you want to protect against the HTML changing and the tests still passing(like it did for my code) you might fetch the `sample.html` when the tests run.

**Comment by tejashah88** [comment]
Good point! It might be worth to also tell Travis to periodically run such tests (which can be done via cron jobs).

**Pull request merged**
